name: Tests
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      BUNDLE_GEMFILE: ${{matrix.gemfile}}
    strategy:
      matrix:
        ruby:
          - head
          - "3.0"
          - "3.1"
          - "3.2"
        gemfile:
          - gemfiles/ar61.gemfile
          - gemfiles/ar70.gemfile
          - gemfiles/ar71.gemfile
    steps:
      - name: Set Up Gems
        uses: actions/checkout@v4
      - name: Set Up Deps
        run: sudo apt-get install libgeos-dev
      - name: Set Up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Test
        run: bundle exec rake
